version: '3'
services:
  manager:
    image: node:8-alpine
    command: npm run start
    working_dir: /app
    volumes:
      - ".:/app"
    ports:
      - "3030:3030"
    user: "${USER_MAPPING:-1000:1000}"
    environment:
      HOME: /app
