version: '3.7'
volumes:
  db-data:
    name: db-data
  web-data:
    name: web-data
services:
  db:
    container_name: odoo_db
    image: postgres:13
    ports:
      - "5080:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: always
  pgadmin:
    container_name: odoo_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.de
      - PGADMIN_DEFAULT_PASSWORD=admin
  mailhog:
    container_name: odoo_mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
  web:
    container_name: odoo_web
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=all --init=social_planning
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - web-data:/var/lib/odoo
    restart: always
